
 --PostgreSQL schema

-- DROP EXISTING TABLES
 DROP TABLE IF EXISTS messages CASCADE;
 DROP TABLE IF EXISTS notifications CASCADE;
 DROP TABLE IF EXISTS reports CASCADE;
 DROP TABLE IF EXISTS memberships CASCADE;
 DROP TABLE IF EXISTS ratings CASCADE;
 DROP TABLE IF EXISTS workout_items CASCADE;
 DROP TABLE IF EXISTS workouts CASCADE;
 DROP TABLE IF EXISTS exercises CASCADE;
 DROP TABLE IF EXISTS machines CASCADE;
 DROP TABLE IF EXISTS equipment CASCADE;
 DROP TABLE IF EXISTS collaborations CASCADE;
 DROP TABLE IF EXISTS collaboration_requests CASCADE;
 DROP TABLE IF EXISTS pricing_packages CASCADE;
 DROP TABLE IF EXISTS licenses CASCADE;
 DROP TABLE IF EXISTS registration_requests CASCADE;
 DROP TABLE IF EXISTS administrators CASCADE;
 DROP TABLE IF EXISTS clients CASCADE;
 DROP TABLE IF EXISTS trainers CASCADE;
 DROP TABLE IF EXISTS user_accounts CASCADE;

-- DROP EXISTING ENUM TYPES
 DROP TYPE IF EXISTS user_type_enum CASCADE;
 DROP TYPE IF EXISTS request_status_enum CASCADE;
 DROP TYPE IF EXISTS collaboration_status_enum CASCADE;
 DROP TYPE IF EXISTS workout_status_enum CASCADE;

-- ENUM TYPES
 CREATE TYPE user_type_enum AS ENUM (
    'ADMIN',
    'TRAINER',
    'CLIENT'
);

 CREATE TYPE request_status_enum AS ENUM (
    'PENDING',
    'APPROVED',
    'REJECTED'
);

 CREATE TYPE collaboration_status_enum AS ENUM (
    'ACTIVE',
    'COMPLETED',
    'TERMINATED'
);

 CREATE TYPE workout_status_enum AS ENUM (
    'SCHEDULED',
    'COMPLETED',
    'CANCELLED'
);

-- USER ACCOUNTS
 CREATE TABLE user_accounts (
                                account_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                username        VARCHAR(100) NOT NULL UNIQUE,
                                password        VARCHAR(255) NOT NULL,
                                user_type       user_type_enum NOT NULL
 );

-- TRAINERS
 CREATE TABLE trainers (
                           trainer_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           account_id          BIGINT NOT NULL UNIQUE
                               REFERENCES user_accounts(account_id) ON DELETE CASCADE,
                           first_name          VARCHAR(100) NOT NULL,
                           last_name           VARCHAR(100) NOT NULL,
                           specialization      VARCHAR(255),
                           average_rating      NUMERIC(3,2) NOT NULL DEFAULT 0
                               CHECK (average_rating BETWEEN 0 AND 5),
                           education           VARCHAR(255),
                           recommendations     TEXT
 );

-- CLIENTS
 CREATE TABLE clients (
                          client_id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          account_id              BIGINT NOT NULL UNIQUE
                              REFERENCES user_accounts(account_id) ON DELETE CASCADE,
                          first_name              VARCHAR(100) NOT NULL,
                          last_name               VARCHAR(100) NOT NULL,
                          height                  NUMERIC(5,2) CHECK (height > 0),
                          weight                  NUMERIC(5,2) CHECK (weight > 0),
                          goal                    TEXT,
                          health_issues           TEXT,
                          workouts_per_week       INTEGER CHECK (workouts_per_week >= 0)
 );

-- ADMINISTRATORS
 CREATE TABLE administrators (
                                 administrator_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 account_id          BIGINT NOT NULL UNIQUE
                                     REFERENCES user_accounts(account_id) ON DELETE CASCADE
 );

 -- MESSAGES
-- One account can send and receive multiple messages.
 CREATE TABLE messages (
                           message_id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           sender_account_id       BIGINT NOT NULL
                               REFERENCES user_accounts(account_id) ON DELETE CASCADE,
                           recipient_account_id    BIGINT NOT NULL
                               REFERENCES user_accounts(account_id) ON DELETE CASCADE,
                           content                 TEXT NOT NULL,
                           is_read                 BOOLEAN NOT NULL DEFAULT FALSE,
                           sent_at                 TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           CHECK (sender_account_id <> recipient_account_id)
 );

-- TRAINER REGISTRATION REQUESTS
 CREATE TABLE registration_requests (
                                        request_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                        trainer_id          BIGINT NOT NULL
                                            REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                                        administrator_id    BIGINT NOT NULL
                                            REFERENCES administrators(administrator_id) ON DELETE RESTRICT,
                                        request_date        DATE NOT NULL DEFAULT CURRENT_DATE,
                                        status              request_status_enum NOT NULL DEFAULT 'PENDING'
 );

-- LICENSES
 CREATE TABLE licenses (
                           license_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           trainer_id          BIGINT NOT NULL
                               REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                           name                VARCHAR(255) NOT NULL,
                           document_type       VARCHAR(100) NOT NULL,
                           issue_date          DATE NOT NULL
 );

-- PRICING PACKAGES
 CREATE TABLE pricing_packages (
                                   pricing_package_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   trainer_id              BIGINT NOT NULL
                                       REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                                   workouts_per_week       INTEGER NOT NULL CHECK (workouts_per_week > 0),
                                   monthly_price           NUMERIC(10,2) NOT NULL CHECK (monthly_price >= 0),
                                   UNIQUE (trainer_id, workouts_per_week)
 );

-- COLLABORATION REQUESTS
 CREATE TABLE collaboration_requests (
                                         request_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                         client_id       BIGINT NOT NULL
                                             REFERENCES clients(client_id) ON DELETE CASCADE,
                                         trainer_id      BIGINT NOT NULL
                                             REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                                         request_date    DATE NOT NULL DEFAULT CURRENT_DATE,
                                         status          request_status_enum NOT NULL DEFAULT 'PENDING'
 );

 -- COLLABORATIONS
-- One pricing package can be selected for multiple collaborations,
-- while each collaboration uses one pricing package.
 CREATE TABLE collaborations (
                                 collaboration_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                 trainer_id             BIGINT NOT NULL
                                     REFERENCES trainers(trainer_id) ON DELETE RESTRICT,
                                 client_id              BIGINT NOT NULL
                                     REFERENCES clients(client_id) ON DELETE RESTRICT,
                                 request_id             BIGINT UNIQUE
                                                               REFERENCES collaboration_requests(request_id) ON DELETE SET NULL,
                                 pricing_package_id     BIGINT NOT NULL
                                     REFERENCES pricing_packages(pricing_package_id) ON DELETE RESTRICT,
                                 start_date             DATE NOT NULL,
                                 end_date               DATE,
                                 status                 collaboration_status_enum NOT NULL DEFAULT 'ACTIVE',
                                 workouts_per_week      INTEGER NOT NULL CHECK (workouts_per_week > 0),
                                 monthly_price          NUMERIC(10,2) NOT NULL CHECK (monthly_price >= 0),
                                 CHECK (end_date IS NULL OR end_date >= start_date)
 );

-- EQUIPMENT
 CREATE TABLE equipment (
                            equipment_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name               VARCHAR(255) NOT NULL UNIQUE
 );

-- MACHINES
 CREATE TABLE machines (
                           machine_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           name               VARCHAR(255) NOT NULL UNIQUE
 );

 -- EXERCISES
-- A trainer creates exercises. An exercise can use at most one piece of equipment
-- and at most one machine.
 CREATE TABLE exercises (
                            exercise_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            trainer_id         BIGINT NOT NULL
                                REFERENCES trainers(trainer_id) ON DELETE RESTRICT,
                            equipment_id       BIGINT
                                                      REFERENCES equipment(equipment_id) ON DELETE SET NULL,
                            machine_id         BIGINT
                                                      REFERENCES machines(machine_id) ON DELETE SET NULL,
                            name               VARCHAR(255) NOT NULL,
                            video_url          TEXT
 );

-- WORKOUTS
 CREATE TABLE workouts (
                           workout_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           collaboration_id   BIGINT NOT NULL
                               REFERENCES collaborations(collaboration_id) ON DELETE CASCADE,
                           scheduled_at       TIMESTAMP NOT NULL,
                           status             workout_status_enum NOT NULL DEFAULT 'SCHEDULED',
                           is_completed       BOOLEAN NOT NULL DEFAULT FALSE,
                           comment            TEXT,
                           workout_rating     INTEGER CHECK (workout_rating BETWEEN 1 AND 5)
 );

 -- WORKOUT ITEMS
-- Association class between a workout and an exercise.
 CREATE TABLE workout_items (
                                workout_item_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                workout_id         BIGINT NOT NULL
                                    REFERENCES workouts(workout_id) ON DELETE CASCADE,
                                exercise_id        BIGINT NOT NULL
                                    REFERENCES exercises(exercise_id) ON DELETE RESTRICT,
                                repetition_count   INTEGER CHECK (repetition_count >= 0),
                                is_completed       BOOLEAN NOT NULL DEFAULT FALSE,
                                item_rating        INTEGER CHECK (item_rating BETWEEN 1 AND 5),
                                comment            TEXT,
                                UNIQUE (workout_id, exercise_id)
 );

-- TRAINER RATINGS
 CREATE TABLE ratings (
                          rating_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          client_id       BIGINT NOT NULL
                              REFERENCES clients(client_id) ON DELETE CASCADE,
                          trainer_id      BIGINT NOT NULL
                              REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                          rating          INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
                          comment         TEXT,
                          rating_date     DATE NOT NULL DEFAULT CURRENT_DATE
 );

-- MEMBERSHIPS
 CREATE TABLE memberships (
                              membership_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              collaboration_id   BIGINT NOT NULL
                                  REFERENCES collaborations(collaboration_id) ON DELETE CASCADE,
                              billing_month      DATE NOT NULL,
                              payment_date       DATE,
                              amount             NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
                              is_paid            BOOLEAN NOT NULL DEFAULT FALSE,
                              UNIQUE (collaboration_id, billing_month)
 );

-- TRAINER REPORTS
 CREATE TABLE reports (
                          report_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          client_id          BIGINT NOT NULL
                              REFERENCES clients(client_id) ON DELETE CASCADE,
                          trainer_id         BIGINT NOT NULL
                              REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                          administrator_id   BIGINT NOT NULL
                              REFERENCES administrators(administrator_id) ON DELETE RESTRICT,
                          description        TEXT NOT NULL,
                          report_date        DATE NOT NULL DEFAULT CURRENT_DATE,
                          status             request_status_enum NOT NULL DEFAULT 'PENDING',
                          resolution         TEXT
 );

-- NOTIFICATIONS
 CREATE TABLE notifications (
                                notification_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                trainer_id         BIGINT NOT NULL
                                    REFERENCES trainers(trainer_id) ON DELETE CASCADE,
                                content            TEXT NOT NULL,
                                notification_date  DATE NOT NULL DEFAULT CURRENT_DATE,
                                type               VARCHAR(100)
 );