
 --PostgreSQL schema


-- DROP POSTOJECIH TABELA

DROP TABLE IF EXISTS notifikacije CASCADE;
DROP TABLE IF EXISTS prijave CASCADE;
DROP TABLE IF EXISTS clanarine CASCADE;
DROP TABLE IF EXISTS ocene CASCADE;
DROP TABLE IF EXISTS sprave CASCADE;
DROP TABLE IF EXISTS rekviziti CASCADE;
DROP TABLE IF EXISTS vezbe CASCADE;
DROP TABLE IF EXISTS treninzi CASCADE;
DROP TABLE IF EXISTS saradnje CASCADE;
DROP TABLE IF EXISTS zahtevi_za_saradnju CASCADE;
DROP TABLE IF EXISTS paketi_cena CASCADE;
DROP TABLE IF EXISTS licence CASCADE;
DROP TABLE IF EXISTS zahtevi_za_registraciju CASCADE;
DROP TABLE IF EXISTS administratori CASCADE;
DROP TABLE IF EXISTS klijenti CASCADE;
DROP TABLE IF EXISTS treneri CASCADE;
DROP TABLE IF EXISTS korisnicki_nalozi CASCADE;


-- DROP POSTOJECIH ENUMA

DROP TYPE IF EXISTS vrsta_korisnika_enum CASCADE;
DROP TYPE IF EXISTS status_zahteva_enum CASCADE;
DROP TYPE IF EXISTS status_saradnje_enum CASCADE;
DROP TYPE IF EXISTS status_treninga_enum CASCADE;

-- ENUMI

CREATE TYPE vrsta_korisnika_enum AS ENUM (
    'ADMIN',
    'TRENER',
    'KLIJENT'
);

CREATE TYPE status_zahteva_enum AS ENUM (
    'CEKANJE',
    'ODOBREN',
    'ODBIJEN'
);

CREATE TYPE status_saradnje_enum AS ENUM (
    'AKTIVNA',
    'ZAVRSENA',
    'PREKINUTA'
);

CREATE TYPE status_treninga_enum AS ENUM (
    'ZAKAZAN',
    'ZAVRSEN',
    'OTKAZAN'
);


-- KORISNICKI NALOZI

CREATE TABLE korisnicki_nalozi (
                                   nalog_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                   korisnicko_ime    VARCHAR(100) NOT NULL UNIQUE,
                                   lozinka           VARCHAR(255) NOT NULL,
                                   vrsta_korisnika   vrsta_korisnika_enum NOT NULL
);


-- TRENERI
-- Svaki trener ima jedan korisnicki nalog

CREATE TABLE treneri (
                         trener_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         nalog_id           BIGINT NOT NULL UNIQUE
                             REFERENCES korisnicki_nalozi(nalog_id) ON DELETE CASCADE,
                         ime                VARCHAR(100) NOT NULL,
                         prezime            VARCHAR(100) NOT NULL,
                         specijalnost       VARCHAR(255),
                         prosecna_ocena     NUMERIC(3,2) NOT NULL DEFAULT 0
                             CHECK (prosecna_ocena BETWEEN 0 AND 5),
                         skolovanje         VARCHAR(255),
                         preporuke          TEXT
);


-- KLIJENTI
-- Svaki klijent ima jedan korisnicki nalog

CREATE TABLE klijenti (
                          klijent_id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          nalog_id                  BIGINT NOT NULL UNIQUE
                              REFERENCES korisnicki_nalozi(nalog_id) ON DELETE CASCADE,
                          ime                       VARCHAR(100) NOT NULL,
                          prezime                   VARCHAR(100) NOT NULL,
                          visina                    NUMERIC(5,2) CHECK (visina > 0),
                          tezina                    NUMERIC(5,2) CHECK (tezina > 0),
                          cilj                      TEXT,
                          broj_treninga_nedeljno    INTEGER CHECK (broj_treninga_nedeljno >= 0),
                          oprema                    TEXT,
                          zdravstveni_problemi      TEXT
);


-- ADMINISTRATORI
-- Svaki administrator ima  jedan korisnicki nalog

CREATE TABLE administratori (
                                administrator_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                nalog_id          BIGINT NOT NULL UNIQUE
                                    REFERENCES korisnicki_nalozi(nalog_id) ON DELETE CASCADE
);


-- ZAHTEVI ZA REGISTRACIJU TRENERA
-- Jedan trener moze imati vise zahteva, zahtev obradjuje jedan admin

CREATE TABLE zahtevi_za_registraciju (
                                         zahtev_id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                         trener_id          BIGINT NOT NULL
                                             REFERENCES treneri(trener_id) ON DELETE CASCADE,
                                         administrator_id   BIGINT NOT NULL
                                             REFERENCES administratori(administrator_id) ON DELETE RESTRICT,
                                         datum              DATE NOT NULL DEFAULT CURRENT_DATE,
                                         status             status_zahteva_enum NOT NULL DEFAULT 'CEKANJE'
);
-- LICENCE
-- Jedan trener moze imati vise licenci

CREATE TABLE licence (
                         licenca_id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         trener_id         BIGINT NOT NULL
                             REFERENCES treneri(trener_id) ON DELETE CASCADE,
                         naziv             VARCHAR(255) NOT NULL,
                         tip_dokumenta     VARCHAR(100) NOT NULL,
                         datum_izdavanja   DATE NOT NULL
);


-- PAKETI CENA
-- Jedan trener moze definisati vise paketa

CREATE TABLE paketi_cena (
                             paket_cene_id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                             trener_id                 BIGINT NOT NULL
                                 REFERENCES treneri(trener_id) ON DELETE CASCADE,
                             broj_treninga_nedeljno    INTEGER NOT NULL CHECK (broj_treninga_nedeljno > 0),
                             cena_mesecno              NUMERIC(10,2) NOT NULL CHECK (cena_mesecno >= 0),
                             UNIQUE (trener_id, broj_treninga_nedeljno)
);


-- ZAHTEVI ZA SARADNJU
-- Svaki zahtev salje jedan klijent jednom treneru

CREATE TABLE zahtevi_za_saradnju (
                                     zahtev_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                     klijent_id   BIGINT NOT NULL
                                         REFERENCES klijenti(klijent_id) ON DELETE CASCADE,
                                     trener_id    BIGINT NOT NULL
                                         REFERENCES treneri(trener_id) ON DELETE CASCADE,
                                     datum        DATE NOT NULL DEFAULT CURRENT_DATE,
                                     status       status_zahteva_enum NOT NULL DEFAULT 'CEKANJE'
);


-- SARADNJE

CREATE TABLE saradnje (
                          saradnja_id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          trener_id                  BIGINT NOT NULL
                              REFERENCES treneri(trener_id) ON DELETE RESTRICT,
                          klijent_id                 BIGINT NOT NULL
                              REFERENCES klijenti(klijent_id) ON DELETE RESTRICT,
                          zahtev_id                  BIGINT UNIQUE
                                                            REFERENCES zahtevi_za_saradnju(zahtev_id) ON DELETE SET NULL,
                          datum_od                   DATE NOT NULL,
                          datum_do                   DATE,
                          status                     status_saradnje_enum NOT NULL DEFAULT 'AKTIVNA',
                          broj_treninga_nedeljno     INTEGER NOT NULL CHECK (broj_treninga_nedeljno > 0),
                          cena_mesecno               NUMERIC(10,2) NOT NULL CHECK (cena_mesecno >= 0),
                          CHECK (datum_do IS NULL OR datum_do >= datum_od)
);


-- TRENINZI
-- Jedna saradnja ima vise treninga

CREATE TABLE treninzi (
                          trening_id       BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                          saradnja_id      BIGINT NOT NULL
                              REFERENCES saradnje(saradnja_id) ON DELETE CASCADE,
                          datum             TIMESTAMP NOT NULL,
                          status            status_treninga_enum NOT NULL DEFAULT 'ZAKAZAN',
                          uradjen           BOOLEAN NOT NULL DEFAULT FALSE,
                          komentar          TEXT,
                          ocena_treninga    INTEGER CHECK (ocena_treninga BETWEEN 1 AND 5)
);


-- VEZBE
-- Jedan trener kreira vise vezbi
-- Jedan trening sadrzi vise vezbi,svaka vezba pripada jednom treningu

CREATE TABLE vezbe (
                       vezba_id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       trener_id          BIGINT NOT NULL
                           REFERENCES treneri(trener_id) ON DELETE RESTRICT,
                       trening_id         BIGINT NOT NULL
                           REFERENCES treninzi(trening_id) ON DELETE CASCADE,
                       naziv              VARCHAR(255) NOT NULL,
                       link_snimka        TEXT,
                       broj_ponavljanja   INTEGER CHECK (broj_ponavljanja >= 0),
                       trajanje           INTEGER CHECK (trajanje >= 0),
                       uradjena           BOOLEAN NOT NULL DEFAULT FALSE
);


-- REKVIZITI
-- Prema kardinalnosti: jedna vezba moze imati vise rekvizita, svaki rekvizit pripada jednoj vezbi

CREATE TABLE rekviziti (
                           rekvizit_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           vezba_id    BIGINT NOT NULL
                               REFERENCES vezbe(vezba_id) ON DELETE CASCADE,
                           naziv       VARCHAR(255) NOT NULL
);

-- SPRAVE
-- jedna vezba moze imati vise sprava, svaka sprava pripada jednoj vezbi

CREATE TABLE sprave (
                        sprava_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        vezba_id  BIGINT NOT NULL
                            REFERENCES vezbe(vezba_id) ON DELETE CASCADE,
                        naziv     VARCHAR(255) NOT NULL
);


-- OCENE
-- Jedan klijent moze dati vise ocena, trener moze primiti vise ocena

CREATE TABLE ocene (
                       ocena_id     BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       klijent_id   BIGINT NOT NULL
                           REFERENCES klijenti(klijent_id) ON DELETE CASCADE,
                       trener_id    BIGINT NOT NULL
                           REFERENCES treneri(trener_id) ON DELETE CASCADE,
                       ocena        INTEGER NOT NULL CHECK (ocena BETWEEN 1 AND 5),
                       komentar     TEXT,
                       datum        DATE NOT NULL DEFAULT CURRENT_DATE
);


-- CLANARINE
-- Jedna saradnja moze imati vise mesecnih clanarina

CREATE TABLE clanarine (
                           clanarina_id   BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           saradnja_id    BIGINT NOT NULL
                               REFERENCES saradnje(saradnja_id) ON DELETE CASCADE,
                           mesec          DATE NOT NULL,
                           datum_uplate   DATE,
                           iznos          NUMERIC(10,2) NOT NULL CHECK (iznos >= 0),
                           placeno        BOOLEAN NOT NULL DEFAULT FALSE,
                           UNIQUE (saradnja_id, mesec)
);

-- PRIJAVE TRENERA

CREATE TABLE prijave (
                         prijava_id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         klijent_id         BIGINT NOT NULL
                             REFERENCES klijenti(klijent_id) ON DELETE CASCADE,
                         trener_id          BIGINT NOT NULL
                             REFERENCES treneri(trener_id) ON DELETE CASCADE,
                         administrator_id   BIGINT NOT NULL
                             REFERENCES administratori(administrator_id) ON DELETE RESTRICT,
                         opis               TEXT NOT NULL,
                         datum              DATE NOT NULL DEFAULT CURRENT_DATE,
                         status             status_zahteva_enum NOT NULL DEFAULT 'CEKANJE',
                         resenje            TEXT
);


-- NOTIFIKACIJE
-- jedan trener moze imati vise notifikacija


CREATE TABLE notifikacije (
                              notifikacija_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              trener_id       BIGINT NOT NULL
                                  REFERENCES treneri(trener_id) ON DELETE CASCADE,
                              sadrzaj         TEXT NOT NULL,
                              datum           DATE NOT NULL DEFAULT CURRENT_DATE,
                              tip             VARCHAR(100)
);